# Generated by Django 4.2.23 on 2025-08-08 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Burger Claim ID"
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=200, verbose_name="Patient Name"),
                ),
                (
                    "billed_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Billed Amount"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Paid Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Denied", "Denied"),
                            ("Under Review", "Under Review"),
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "insurer_name",
                    models.CharField(max_length=100, verbose_name="Insurer Name"),
                ),
                ("discharge_date", models.DateField(verbose_name="Discharge Date")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Burger Claim",
                "verbose_name_plural": "Burger Claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Department"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Note Content")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="claims.claim",
                        verbose_name="Burger Claim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Burger Note",
                "verbose_name_plural": "Burger Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=200, verbose_name="Flag Reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="claims.claim",
                        verbose_name="Burger Claim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Burger Flag",
                "verbose_name_plural": "Burger Flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpt_codes",
                    models.TextField(blank=True, null=True, verbose_name="CPT Codes"),
                ),
                (
                    "denial_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Denial Reason"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="claims.claim",
                        verbose_name="Burger Claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Burger Claim Detail",
                "verbose_name_plural": "Burger Claim Details",
            },
        ),
    ]
