# Generated by Django 5.2.5 on 2025-08-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claim",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
            },
        ),
        migrations.AlterModelOptions(
            name="claimdetail",
            options={
                "verbose_name": "Claim Detail",
                "verbose_name_plural": "Claim Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flag",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Flag",
                "verbose_name_plural": "Flags",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="Claim ID"),
        ),
        migrations.AlterField(
            model_name="claimdetail",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="claims.claim",
                verbose_name="Claim",
            ),
        ),
        migrations.AlterField(
            model_name="flag",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="claims.claim",
                verbose_name="Claim",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="claims.claim",
                verbose_name="Claim",
            ),
        ),
    ]
