# Generated by Django 4.2.23 on 2025-08-22 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("claims", "0002_alter_claim_options_alter_claimdetail_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_claims",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("reviewer", "Claims Reviewer"),
                    ("admin", "Administrator"),
                    ("supervisor", "Supervisor"),
                ],
                default="reviewer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
